service: sms-lambda

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  region: eu-central-1

plugins:
  - serverless-offline
  - serverless-dotenv-plugin

functions:
  client-sms:
    handler: sls.run
    events:
      - http:
          path: /
          method: ANY
          cors: true
      - http:
          path: /{proxy+}
          method: ANY
          cors: true
